extend type Badge {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Badge", purpose: IMPLICIT_KEY_FIELD)
}
extend type LeaderboardEntry {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "LeaderboardEntry", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `LeaderboardEntry`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "LeaderboardEntry.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Peak {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Peak", purpose: IMPLICIT_KEY_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type UserBadge {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "UserBadge", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `UserBadge`.`badge`. It must match the value of `Badge`.`id`. See `@ref` for how to customize it.
  """
  badgeId: UUID! @fdc_generated(from: "UserBadge.badge", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UserBadge`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "UserBadge.user", purpose: IMPLICIT_REF_FIELD)
}
extend type UserPeak {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "UserPeak", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `UserPeak`.`peak`. It must match the value of `Peak`.`id`. See `@ref` for how to customize it.
  """
  peakId: UUID! @fdc_generated(from: "UserPeak.peak", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UserPeak`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "UserPeak.user", purpose: IMPLICIT_REF_FIELD)
}
