// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHVTEOApW3O6A3XQOyJpv94OWGnZkXVjY',
    appId: '1:154994703214:web:188ee9a070728b669a1f7f',
    messagingSenderId: '154994703214',
    projectId: 'pestenori-bc7a8',
    authDomain: 'pestenori-bc7a8.firebaseapp.com',
    storageBucket: 'pestenori-bc7a8.firebasestorage.app',
    measurementId: 'G-GHJPY4S0V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR9xc7Br_1_R0vYgytIm9j3P6prqUYhPU',
    appId: '1:154994703214:android:ccb495b1c29ddde79a1f7f',
    messagingSenderId: '154994703214',
    projectId: 'pestenori-bc7a8',
    storageBucket: 'pestenori-bc7a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx85BfBKQIRNcg-TQzN2kYw_1NVCzBea8',
    appId: '1:154994703214:ios:7464a349afcff28b9a1f7f',
    messagingSenderId: '154994703214',
    projectId: 'pestenori-bc7a8',
    storageBucket: 'pestenori-bc7a8.firebasestorage.app',
    iosClientId: '154994703214-5u206p43nn223etg23sns61o0dghhfpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pesteNori',
  );
}
